[package]
name = "dabridge"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2", features = ["derive"] }
paho-mqtt = { git = "https://github.com/eclipse/paho.mqtt.rust.git", rev = "v0.11.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tungstenite = "0.17"
bytes = "1.3.0"
# exitcode = "1.1.2"
